GET http://localhost:8080/authors

###
GET http://localhost:8080/authors/2

###
POST http://localhost:8080/authors
Content-Type: application/json

{
    "name": "Nate",
    "age": 55,
    "genre": "computer"
}

###
GET http://localhost:8080/books

###
GET http://localhost:8080/books/1

###
GET http://localhost:8080/books/computer%20programming/title