GET http://localhost:8080/authors

###
GET http://localhost:8080/authors/2

###
POST http://localhost:8080/authors
Content-Type: application/json

{
    "name": "Nate",
    "age": 55,
    "genre": "computer"
}

###
GET http://localhost:8080/books

###
GET http://localhost:8080/books/1

###
GET http://localhost:8080/books/computer%20programming/title


###
GET http://localhost:8080/courses/1

###
GET http://localhost:8080/courses

###
POST http://localhost:8080/courses
Content-Type: application/json

{
    "title": "Database Management",
    "category": "computer"
}

###
DELETE http://localhost:8080/courses/1


###
GET http://localhost:8080/students

###
GET http://localhost:8080/students/5

###
POST http://localhost:8080/students
Content-Type: application/json

{
    "name": "micheal",
    "address": {
        "street": "100 ocean street",
        "city": "Miami",
        "state": "FL",
        "zipCode": 2001
    }
}


###
POST http://localhost:8080/students/5/enroll
Content-Type: application/json

{
    "title": "Database Management",
    "category": "computer"
}

###
POST http://localhost:8080/students/5/remove
Content-Type: application/json

{
    "title": "Database Management",
    "category": "computer"
}